const data=[ { img: 'https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg',
    title: 'Nike Air Vapormax Plus',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '200',
    company: 'Nike',
    color: 'red',
    category: 'sneakers',
    totalStar: 3,
    id: 1 },
  { img: 'https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg',
    title: 'Nike Waffle One Sneaker',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '200',
    company: 'Nike',
    color: 'green',
    category: 'sneakers',
    totalStar: 5,
    id: 2 },
  { img: 'https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg',
    title: 'Nike Running Shoe',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '200',
    company: 'Adidas',
    color: 'black',
    category: 'sneakers',
    totalStar: 2,
    id: 3 },
  { img: 'https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg',
    title: 'Flat Slip On Pumps',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '200',
    company: 'Vans',
    color: 'green',
    category: 'flats',
    totalStar: 4,
    id: 4 },
  { img: 'https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg',
    title: 'Knit Ballet Flat',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '50',
    company: 'Adidas',
    color: 'black',
    category: 'flats',
    totalStar: 5,
    id: 5 },
  { img: 'https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg',
    title: 'Loafer Flats',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '50',
    company: 'Vans',
    color: 'white',
    category: 'flats',
    totalStar: 3,
    id: 6 },
  { img: 'https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg',
    title: 'Nike Zoom Freak',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '200',
    company: 'Nike',
    color: 'green',
    category: 'sneakers',
    totalStar: 4,
    id: 7 },
  { img: 'https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg',
    title: 'Nike Men\'s Sneaker',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '200',
    company: 'Adidas',
    color: 'blue',
    category: 'sneakers',
    totalStar: 2,
    id: 8 },
  { img: 'https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg',
    title: 'PUMA BLACK-OCE',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '150',
    company: 'Puma',
    color: 'green',
    category: 'sneakers',
    totalStar: 5,
    id: 9 },
  { img: 'https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg',
    title: 'Pacer Future Sneaker',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '150',
    company: 'Puma',
    color: 'red',
    category: 'sneakers',
    totalStar: 3,
    id: 10 },
  { img: 'https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg',
    title: 'Unisex-Adult Super',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '150',
    company: 'Puma',
    color: 'black',
    category: 'sneakers',
    totalStar: 4,
    id: 11 },
  { img: 'https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg',
    title: 'Roma Basic Sneaker',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '150',
    company: 'Puma',
    color: 'white',
    category: 'sneakers',
    totalStar: 5,
    id: 12 },
  { img: 'https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg',
    title: 'Pacer Future Doubleknit',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '150',
    company: 'Puma',
    color: 'black',
    category: 'sneakers',
    totalStar: 4,
    id: 13 },
  { img: 'https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg',
    title: 'Fusion Evo Golf Shoe',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '100',
    company: 'Puma',
    color: 'green',
    category: 'sneakers',
    totalStar: 5,
    id: 14 },
  { img: 'https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg',
    title: 'Rainbow Chex Skate',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '100',
    company: 'Vans',
    color: 'red',
    category: 'flats',
    totalStar: 3,
    id: 15 },
  { img: 'https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg',
    title: 'Low-Top Trainers',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '100',
    company: 'Vans',
    color: 'white',
    category: 'sandals',
    totalStar: 2,
    id: 16 },
  { img: 'https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg',
    title: 'Vans Unisex Low-Top',
    reviews: '(123 reviews)',
    prevPrice: '140,00',
    newPrice: '100',
    company: 'Vans',
    color: 'blue',
    category: 'sandals',
    totalStar: 4,
    id: 17 } ]
export default data;